### ISSUE TITLE
[BUG]: EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by TimPietrusky** [failfa-st/LoRAdo#5]
**Describe the bug** 
I have LoRAdo installed on drive **D:** on Windows. I leave all default configurations, uploaded 5 images, added captions and clicked on "prepare". Then it takes some time, nothing is happening in the UI besides the "loading" animation. In the CLI I see the following error instantly:

```
[Error: EXDEV: cross-device link not permitted, rename 'C:\Users\NERDDI~1\AppData\Local\Temp\34cc4814dea94a20066614202' -> 'D:\dev\js\failfast\LoRAdo\training\n3rdd1sc0\dataset\n3rdd1sc0--0003.jpg'] {
  errno: -4037,
  code: 'EXDEV',
  syscall: 'rename',
  path: 'C:\\Users\\NERDDI~1\\AppData\\Local\\Temp\\34cc4814dea94a20066614202',
  dest: 'D:\\dev\\js\\failfast\\LoRAdo\\training\\n3rdd1sc0\\dataset\\n3rdd1sc0--0003.jpg'
}
```

Then after some more time, the "loading"-animation on the "prepare"-button is gone and I get this error in the CLI: 

```
ypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at async invokeRequest (D:\dev\js\failfast\LoRAdo\node_modules\next\dist\server\lib\server-ipc\invoke-request.js:17:12)
    at async invokeRender (D:\dev\js\failfast\LoRAdo\node_modules\next\dist\server\lib\router-server.js:253:29)
    at async handleRequest (D:\dev\js\failfast\LoRAdo\node_modules\next\dist\server\lib\router-server.js:446:24)
    at async requestHandler (D:\dev\js\failfast\LoRAdo\node_modules\next\dist\server\lib\router-server.js:463:13)
    at async Server.<anonymous> (D:\dev\js\failfast\LoRAdo\node_modules\next\dist\server\lib\start-server.js:117:13) {
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (D:\dev\js\failfast\LoRAdo\node_modules\next\dist\compiled\undici\index.js:1:62578)
      at Timeout.onTimeout [as _onTimeout] (D:\dev\js\failfast\LoRAdo\node_modules\next\dist\compiled\undici\index.js:2:269659)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}
```

The dataset is created, I also see the captions and the config.json. Just the images are not copied. 

**Expected behavior**
I can install LoRAdo on any drive I want and clicking on "prepare" will actually copy the images that I uploaded into the generated dataset. 

**Versions (please complete the following information):** 

- Browser: Chrome 115.0.5790.170 (Official Build) (arm64)
- Node.js: v18.15.0
- OS: Windows 11
- LoRAdo: https://github.com/failfa-st/LoRAdo/releases/tag/v0.1.0-alpha.3

**Comment by pixelass** [comment]
this should be fixed by now

**Comment by TimPietrusky** [comment]
@pixelass tested and works! Thank you.
